import type { Express } from 'express';
import { authRouter } from './auth.routes.js';
import { portfoliosRouter } from './portfolios.routes.js';
import { portfolioGroupsRouter } from './portfolioGroups.routes.js';
import { transactionsRouter } from './transactions.routes.js';
import { assetsRouter } from './assets.routes.js';
import { importsRouter } from './imports.routes.js';
import { ingestionFailuresRouter } from './ingestionFailures.routes.js';
import { connectorsRouter } from './connectors.routes.js';
import { mailboxesRouter } from './mailboxes.routes.js';
import { gmailRouter } from './gmail.routes.js';
import { gmailScanRouter } from './gmailScan.routes.js';
import { reportsRouter } from './reports.routes.js';
import { casRouter } from './cas.routes.js';
import { canonicalEventsRouter } from './canonicalEvents.routes.js';
import { monitoredSendersRouter } from './monitoredSenders.routes.js';
import { ingestionRouter } from './ingestion.routes.js';
import { vehiclesRouter } from './vehicles.routes.js';
import { cashFlowsRouter } from './cashflows.routes.js';
import { rentalRouter } from './rental.routes.js';
import { insuranceRouter } from './insurance.routes.js';
import { accountingRouter } from './accounting.routes.js';
import { alertsRouter } from './alerts.routes.js';
import { dashboardRouter } from './dashboard.routes.js';
import { mfCentralRouter } from './mfCentral.routes.js';
import { mfCasMailbackRouter } from './mfCasMailback.routes.js';
import { mfCasparserRouter } from './mfCasparser.routes.js';
import { foRouter } from './fo.routes.js';
import { catalogRouter, valuationRouter } from './valuation.routes.js';
import { documentsRouter } from './documents.routes.js';
import { loansRouter } from './loans.routes.js';
import { creditCardsRouter } from './creditCards.routes.js';
import { bankAccountsRouter } from './bankAccounts.routes.js';
import { realEstateRouter } from './realEstate.routes.js';
import { pfRouter } from './pf.routes.js';
import { forexRouter } from './forex.routes.js';
import { taxRouter } from './tax.routes.js';
import { analyticsRouter } from './analytics.routes.js';
import { userPreferencesRouter } from './userPreferences.routes.js';
import { notificationsRouter } from './notifications.routes.js';
import { corporateActionsRouter } from './corporateActions.routes.js';
import { goalsRouter } from './goals.routes.js';
import { finfactorRouter } from './finfactor.routes.js';

export function registerRoutes(app: Express): void {
  app.use('/api/auth', authRouter);
  app.use('/api/portfolios', portfoliosRouter);
  app.use('/api/portfolio-groups', portfolioGroupsRouter);
  app.use('/api/transactions', transactionsRouter);
  app.use('/api/assets', assetsRouter);
  app.use('/api/imports', importsRouter);
  app.use('/api/ingestion-failures', ingestionFailuresRouter);
  app.use('/api/connectors', connectorsRouter);
  app.use('/api/mailboxes', mailboxesRouter);
  app.use('/api/gmail', gmailRouter);
  app.use('/api/gmail', gmailScanRouter);
  app.use('/api/reports', reportsRouter);
  app.use('/api/cas', casRouter);
  app.use('/api/canonical-events', canonicalEventsRouter);
  app.use('/api/monitored-senders', monitoredSendersRouter);
  app.use('/api/ingestion', ingestionRouter);
  app.use('/api/vehicles', vehiclesRouter);
  app.use('/api/cashflows', cashFlowsRouter);
  app.use('/api/rental', rentalRouter);
  app.use('/api/insurance', insuranceRouter);
  app.use('/api/accounting', accountingRouter);
  app.use('/api/alerts', alertsRouter);
  app.use('/api/dashboard', dashboardRouter);
  app.use('/api/mf-central', mfCentralRouter);
  app.use('/api/mf-cas-mailback', mfCasMailbackRouter);
  app.use('/api/mf-casparser', mfCasparserRouter);
  app.use('/api/fo', foRouter);
  app.use('/api/catalog', catalogRouter);
  app.use('/api/valuations', valuationRouter);
  app.use('/api/documents', documentsRouter);
  app.use('/api/loans', loansRouter);
  app.use('/api/credit-cards', creditCardsRouter);
  app.use('/api/bank-accounts', bankAccountsRouter);
  app.use('/api/real-estate', realEstateRouter);
  app.use('/api/epfppf', pfRouter);
  app.use('/api/forex', forexRouter);
  app.use('/api/tax', taxRouter);
  app.use('/api/analytics', analyticsRouter);
  app.use('/api/user/preferences', userPreferencesRouter);
  app.use('/api/notifications', notificationsRouter);
  app.use('/api/corporate-actions', corporateActionsRouter);
  app.use('/api/goals', goalsRouter);
  app.use('/api/integrations/finfactor', finfactorRouter);
}
